### ISSUE TITLE
Error loading "i'm not robot" when invalid password validation 

### ISSUE THREAD

**Issue by cadavidgomez** [BitArmory/ReCaptcha#3] opened 2019-07-10 21:35 UTC
I’m implementing the version 2 over the Identity scaffolding login (ASP.NET MVC Core), so when I input an incorrect password the page reloads and doesn’t load the ReCaptcha again.
![image](https://user-images.githubusercontent.com/28210022/61006401-dbec5600-a32f-11e9-9dd7-b7272a4e2e84.png)
Then submit and i get the form like this
![image](https://user-images.githubusercontent.com/28210022/61006758-b0b63680-a330-11e9-93a8-b264d8e20f38.png)

Hope you can help me about this

**Comment by bchavez** [comment] 2019-07-10 21:53
Hi @cadavidgomez,

Thank you for the clarification. I suspect the issue is something related to HTML and JavaScript as your view is being rendered through Razor.

I don't think your issue is related to this ReCaptcha library because this library only does validation and doesn't have anything user interface related.

Perhaps you have a `if( condition ) else `  somewhere in your Razor View that's not loading the ReCaptcha JavaScript.

**Comment by bchavez** [comment] 2019-07-11 22:31
Hey @cadavidgomez ,

I'm going to close the issue now. Feel free to continue the conversation if you find there's an issue with the library.

Thanks,
Brian

**Closed by bchavez** 2019-07-11 22:31 UTC
